package test.model;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.ID
     *
     * @mbggenerated Sat Dec 07 00:31:06 HKT 2013
     */
    private Integer ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.COUNT
     *
     * @mbggenerated Sat Dec 07 00:31:06 HKT 2013
     */
    private Integer COUNT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.DISCOUNT
     *
     * @mbggenerated Sat Dec 07 00:31:06 HKT 2013
     */
    private Double DISCOUNT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.HAS_SENT
     *
     * @mbggenerated Sat Dec 07 00:31:06 HKT 2013
     */
    private Byte HAS_SENT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.CUSTOMER_ID
     *
     * @mbggenerated Sat Dec 07 00:31:06 HKT 2013
     */
    private Integer CUSTOMER_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.BILL_ID
     *
     * @mbggenerated Sat Dec 07 00:31:06 HKT 2013
     */
    private Integer BILL_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.ORDER_ADDRESS
     *
     * @mbggenerated Sat Dec 07 00:31:06 HKT 2013
     */
    private String ORDER_ADDRESS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.ID
     *
     * @return the value of ORDERS.ID
     *
     * @mbggenerated Sat Dec 07 00:31:06 HKT 2013
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.ID
     *
     * @param ID the value for ORDERS.ID
     *
     * @mbggenerated Sat Dec 07 00:31:06 HKT 2013
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.COUNT
     *
     * @return the value of ORDERS.COUNT
     *
     * @mbggenerated Sat Dec 07 00:31:06 HKT 2013
     */
    public Integer getCOUNT() {
        return COUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.COUNT
     *
     * @param COUNT the value for ORDERS.COUNT
     *
     * @mbggenerated Sat Dec 07 00:31:06 HKT 2013
     */
    public void setCOUNT(Integer COUNT) {
        this.COUNT = COUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.DISCOUNT
     *
     * @return the value of ORDERS.DISCOUNT
     *
     * @mbggenerated Sat Dec 07 00:31:06 HKT 2013
     */
    public Double getDISCOUNT() {
        return DISCOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.DISCOUNT
     *
     * @param DISCOUNT the value for ORDERS.DISCOUNT
     *
     * @mbggenerated Sat Dec 07 00:31:06 HKT 2013
     */
    public void setDISCOUNT(Double DISCOUNT) {
        this.DISCOUNT = DISCOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.HAS_SENT
     *
     * @return the value of ORDERS.HAS_SENT
     *
     * @mbggenerated Sat Dec 07 00:31:06 HKT 2013
     */
    public Byte getHAS_SENT() {
        return HAS_SENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.HAS_SENT
     *
     * @param HAS_SENT the value for ORDERS.HAS_SENT
     *
     * @mbggenerated Sat Dec 07 00:31:06 HKT 2013
     */
    public void setHAS_SENT(Byte HAS_SENT) {
        this.HAS_SENT = HAS_SENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.CUSTOMER_ID
     *
     * @return the value of ORDERS.CUSTOMER_ID
     *
     * @mbggenerated Sat Dec 07 00:31:06 HKT 2013
     */
    public Integer getCUSTOMER_ID() {
        return CUSTOMER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.CUSTOMER_ID
     *
     * @param CUSTOMER_ID the value for ORDERS.CUSTOMER_ID
     *
     * @mbggenerated Sat Dec 07 00:31:06 HKT 2013
     */
    public void setCUSTOMER_ID(Integer CUSTOMER_ID) {
        this.CUSTOMER_ID = CUSTOMER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.BILL_ID
     *
     * @return the value of ORDERS.BILL_ID
     *
     * @mbggenerated Sat Dec 07 00:31:06 HKT 2013
     */
    public Integer getBILL_ID() {
        return BILL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.BILL_ID
     *
     * @param BILL_ID the value for ORDERS.BILL_ID
     *
     * @mbggenerated Sat Dec 07 00:31:06 HKT 2013
     */
    public void setBILL_ID(Integer BILL_ID) {
        this.BILL_ID = BILL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.ORDER_ADDRESS
     *
     * @return the value of ORDERS.ORDER_ADDRESS
     *
     * @mbggenerated Sat Dec 07 00:31:06 HKT 2013
     */
    public String getORDER_ADDRESS() {
        return ORDER_ADDRESS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.ORDER_ADDRESS
     *
     * @param ORDER_ADDRESS the value for ORDERS.ORDER_ADDRESS
     *
     * @mbggenerated Sat Dec 07 00:31:06 HKT 2013
     */
    public void setORDER_ADDRESS(String ORDER_ADDRESS) {
        this.ORDER_ADDRESS = ORDER_ADDRESS == null ? null : ORDER_ADDRESS.trim();
    }
}