package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.Order;
import test.model.OrderExample;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS
     *
     * @mbggenerated Mon Dec 09 11:08:53 HKT 2013
     */
    int countByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS
     *
     * @mbggenerated Mon Dec 09 11:08:53 HKT 2013
     */
    int deleteByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS
     *
     * @mbggenerated Mon Dec 09 11:08:53 HKT 2013
     */
    int deleteByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS
     *
     * @mbggenerated Mon Dec 09 11:08:53 HKT 2013
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS
     *
     * @mbggenerated Mon Dec 09 11:08:53 HKT 2013
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS
     *
     * @mbggenerated Mon Dec 09 11:08:53 HKT 2013
     */
    List<Order> selectByExampleWithBLOBs(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS
     *
     * @mbggenerated Mon Dec 09 11:08:53 HKT 2013
     */
    List<Order> selectByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS
     *
     * @mbggenerated Mon Dec 09 11:08:53 HKT 2013
     */
    Order selectByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS
     *
     * @mbggenerated Mon Dec 09 11:08:53 HKT 2013
     */
    int updateByExampleSelective(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS
     *
     * @mbggenerated Mon Dec 09 11:08:53 HKT 2013
     */
    int updateByExampleWithBLOBs(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS
     *
     * @mbggenerated Mon Dec 09 11:08:53 HKT 2013
     */
    int updateByExample(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS
     *
     * @mbggenerated Mon Dec 09 11:08:53 HKT 2013
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS
     *
     * @mbggenerated Mon Dec 09 11:08:53 HKT 2013
     */
    int updateByPrimaryKeyWithBLOBs(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS
     *
     * @mbggenerated Mon Dec 09 11:08:53 HKT 2013
     */
    int updateByPrimaryKey(Order record);
}